name: "Publish"

on:
  release:
    types: ["published"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Install dependencies"
        run: |
          npm install
          npm install -g vsce

      - name: "Deploy"
        run: "vsce publish -p $PUBLISH_TOKEN"
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
