name: "Publish"

on:
  release:
    types: ["published"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $PUBLISH_TOKEN"
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
