name: "Publish"

on:
  release:
    types: ["published"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install -g vsce
      - name: Publish
        run: vsce publish -p ${{ secrets.PUBLISH_TOKEN }}
