name: "Publish"

on:
  release:
    types: ["published"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
        run: npm install -g vsce
      - name: Publish
      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $PUBLISH_TOKEN"
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
